version: "3.8"
services:
  api:
    build: ./services/api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/db
      - REDIS_URL=redis://redis:6379/0
      - S3_BUCKET=local-bucket
    depends_on:
      - db
      - redis

  worker:
    build: ./services/worker
    command: celery -A worker.tasks worker --loglevel=info
    depends_on:
      - redis
      - db

  redis:
    image: redis:7

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
